# Generated by Django 3.1.5 on 2021-01-15 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('description', models.TextField(verbose_name='Review Description')),
                ('review_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewof', to=settings.AUTH_USER_MODEL, verbose_name='Review Of')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewedby', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'userreview',
                'verbose_name_plural': 'userreviews',
            },
        ),
    ]
