# Generated by Django 3.1.5 on 2021-01-18 13:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('miam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('advertisement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miam.advertisement', verbose_name='Advertisement')),
                ('bookmarked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buyerprofile', verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Advertisement Bookmark',
                'verbose_name_plural': 'Advertisement Bookmarks',
            },
        ),
    ]
