# Generated by Django 3.1.5 on 2021-01-15 04:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('miam', '0002_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('description', models.TextField(verbose_name='Review Description')),
                ('advertisement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miam.advertisement', verbose_name='Advertisement')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buyerprofile', verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
