# Generated by Django 3.1.5 on 2021-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miam', '0003_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=100, verbose_name='Total Price'),
            preserve_default=False,
        ),
    ]
