# Generated by Django 3.1.4 on 2021-01-02 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], default=django.utils.timezone.now, max_length=50, verbose_name='User Type'),
            preserve_default=False,
        ),
    ]
